apiVersion: v1
kind: Service
metadata:
  labels:
    app: weblogic-crm
  name: weblogic-crm
  namespace: yewuceshi
spec:
  type: NodePort
  ports:
  - port: 7010
    targetPort: 7010
    nodePort: 30051
  selector:
    app: weblogic-crm
  sessionAffinity: ClientIP
