apiVersion: v1
kind: Service
metadata:
  labels:
    app: vsdpts
  name: vsdpts-default
  namespace: yewuceshi
spec:
  ports:
  - nodePort: 30031
    name: tcp-30031-8080-7yamd
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vsdpts
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
