apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: weblogic-micro
  name: weblogic-micro
  namespace: yewuceshi
spec:
  replicas:
  selector:
    matchLabels:
      app: weblogic-micro
  template:
    metadata:
      labels:
        app: weblogic-micro
    spec:
      volumes:
       - name: logdata
         nfs:
          server: 192.168.88.136
          path: /docker/logdata_volumes/MICRO
      containers:
      - image: 192.168.88.136:5000/weblogic11_micro:20171115
        imagePullPolicy: Always
        volumeMounts:
        - name: logdata
          mountPath: /home/logs
        name: http
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          httpGet:
            path: /console
            port: 7010
          initialDelaySeconds: 90
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /console
            port: 7010
          initialDelaySeconds: 90
          timeoutSeconds: 1
