apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: yewuceshi
spec:
  type: NodePort
  ports:
  - port: 15672
    targetPort: 15672 
    nodePort: 32011
    name: web
  - port: 25672
    targetPort: 25672
    nodePort: 32012
    name: rabbitmq1
  - port: 5672
    targetPort: 5672
    nodePort: 32013
    name: rabbitmq2
  - port: 4369
    targetPort: 4369
    nodePort: 32014
    name: rabbitmq3
  - port: 5671
    targetPort: 5671
    nodePort: 32015
    name: rabbitmq4
  selector:
    app: rabbitmq
