apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: weblogic1-vsdp
  name: weblogic1-vsdp
  namespace: yewuceshi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weblogic1-vsdp
  template:
    metadata:
      labels:
        app: weblogic1-vsdp
    spec:
      containers:
      - image: 192.168.88.136:5000/busybox:20171030
        name: weblogic1-vsdp
        volumeMounts:
        - mountPath: /home
          name: my-pvc
      volumes:
      - name: my-pvc
        persistentVolumeClaim:
          claimName: pvc-nfs
