apiVersion: v1
kind: Service
metadata:
  labels:
    app: weblogic-soip
  name: weblogic-soip
  namespace: yewuceshi
spec:
  type: NodePort
  ports:
  - port: 7010
    targetPort: 7010
    nodePort: 30021
  selector:
    app: weblogic-soip
  sessionAffinity: ClientIP
